trigger: none
pool:
  #vmImage: windows-latest
  name: Hygien_BOT
  demands:
    - agent.name -equals pepwap25520W
variables:
- group: SQL_CR_BLOB_CR
parameters:
  - name: Subscription_Names
    type: string
    default: 'all'

  - name: Reporting_Bot
    displayName: 'Reporting BotName'
    type: string
    default: 'N/A'
    values:
      - 'N/A'
      - 'azure_application_gateway_health_status.py'
      - 'azure_application_gateway_wafv2_listner_limit_details_100.py'
      - 'azure_application_gateway_wafv2_listner_limit_details_40.py'
      - 'azure_cors_origin_resource_sharing.py'
      - 'azure_empty_load_balancer_applicatio_gateway.py'
      - 'azure_firewall_allowed_public_ip_in_storage_keyvault_eventhub_SQL.py'
      - 'azure_key_vault_soft_delete_status.py'
      - 'azure_load_balancer_helth_status.py'
      - 'azure_network_security_group_any_port_open_to_public.py'
      - 'azure_nsg_seven_days_modification_track_changes.py'
      - 'azure_orphans_snapshot.py'
      - 'azure_private_endpoint_connection_status.py'
      - 'azure_route_table_seven_days_modification_track_changes.py'
      - 'azure_services_https_not_enabled_with_webapp_functionapp_api.py'
      - 'azure_vm_deletion_activity_log.py'
      - 'azure_vm_stop_deallocated_status.py'
      - 'azure_vm_with_more_asg.py'
      - 'azure_vm_without_asg.py'
      - 'azure_vnet_details_without_shared_services_vnet.py'
      - 'azure_vnet_dns_standard_order_details.py'
      - 'azure_rbac_duplicate_access_details.py'
      - 'azure_blob_storage_soft_delete_retention_period_status.py'
      - 'azure_services_diagnostic_setting_details_RG.py'
      - 'azure_services_diagnostic_setting_details_SUB.py'
      - 'azure_network_security_group_ftp_port_open_to_public_auditmode.py'
      - 'azure_vm_stopped_activity.py'
      - 'azure_vm_with_asr.py'
      - 'azure_vm_property_details.py'
      - 'azure_nsg_without_common_security_groups.py'
      - 'azure_enterprises_private_endpoint_having_azure_A_record_associted_private_dns_zone.py'
      - 'azure-unknown-rbac-role.py'
      - 'azure_policy_initiative_assignment_modified.py'
      - 'azure_unused_subscriptions.py'
      - 'azure_keyvault_having_wiz_principle_name.py'
      - 'azure_empty_resource_groups.py'
      - 'azure_priviledged_access_bot.py'
      - 'azure_private_dns_zones_outside_of_standard_rg.py'
      - 'azure_nsg_common_rule_modification_activity.py'
      - 'azure_asg_nsg_not_mapped_with_correct_resource_group.py'
      - 'azure_storage_account_logging_disabled.py'
      - 'azure_empty_route_table.py'
      - 'azure_nsg_without_subnet_and_network_interface_card.py'
      - 'azure_vm_cpu_quota_limit.py'
      - 'azure_nsg_ip_limit.py'
      - 'azure_rbac_limit_on_subscription.py'
      - 'azure_nsg_admin_port_open_to_public.py'
      - 'azure_nsg_rule_limit.py'
  

jobs:
- job: Build
  timeoutInMinutes: 200  # Adjust the timeout as needed, e.g., 120 minutes
  steps:      
    - task: CmdLine@2
      inputs:
        script: |
          "C:\Program Files\Microsoft SDKs\Azure\CLI2\python.exe" -m pip install --upgrade pip
          "C:\Program Files\Microsoft SDKs\Azure\CLI2\python.exe" -m pip install -r ./Dependencies/Install_Modules.txt
      displayName: 'Install Python Modules'

    - task: AzureCLI@2
      displayName: 'Execute Reporting Bot'
      inputs:
        azureSubscription: 'pep-prod-bot-automation-spn'
        scriptType: 'ps'
        scriptLocation: 'inlineScript'
        addSpnToEnvironment: true
        inlineScript: |
          $env:AZURE_TENANT_ID = $tenantId
          $env:AZURE_CLIENT_ID = $servicePrincipalId
          $env:AZURE_CLIENT_SECRET = $servicePrincipalKey
          $env:AZURE_AUTHORITY_HOST = "login.microsoftonline.com"   
          python ./Main_functions/Reporting/${{ parameters.Reporting_Bot }} ${{ parameters.Subscription_Names }}   
        
    
